### ISSUE TITLE
does not start on arm64

### ISSUE THREAD

**Issue by derEremit** [BytemarkHosting/docker-smtp#10]
This is used in plausible analytics docker compose

```
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always
```

it restarts with

```
exec /usr/local/bin/docker-entrypoint.sh: exec format error
```

I am running on oracle cloud arm

```
Linux instance-20221026-0418 5.15.0-1040-oracle #46-Ubuntu SMP Fri Jul 14 21:47:21 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
